name: Deploy Frotend Link Shortener

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. Install dependencies
      - name: Install dependencies
        working-directory: app
        run: npm install

      # 4. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 5. terraform init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # 6. terraform apply
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      # 7. Permisos al script
      - name: Give execute permission to deploy.sh
        working-directory: terraform
        run: chmod +x deploy.sh

      # 8. Ejecutar deploy
      - name: Run deploy script
        working-directory: terraform
        run: ./deploy.sh
